//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByggemarkedEFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookinger
    {
        public int BookingId { get; set; }
        public string Status { get; set; }
        public decimal TotalPris { get; set; }
        public System.DateTime PeriodeStart { get; set; }
        public System.DateTime PeriodeSlut { get; set; }
        public int KundeId { get; set; }
        public int VaerktoejId { get; set; }
    
        public virtual Kunder Kunder { get; set; }
        public virtual Vaerktoej Vaerktoej { get; set; }

        override
        public string ToString()
        {
            return $"{BookingId}, {Vaerktoej.Type}";
        }

        public string CompareTo(string b)
        {
            return this.CompareTo(b);
        }
    }
}
